# Generated by Django 4.2.16 on 2024-11-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_post_downvotes_post_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/default.jpg.webp', null=True, upload_to='images/'),
        ),
    ]
