# Generated by Django 4.2.16 on 2024-12-05 12:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='images/default.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
