# Generated by Django 4.2.16 on 2024-12-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_sugars', '0001_initial'),
    ]

    operations = [
    ]
